(task): "Definição de Rotas da API"
unb-mds/2023-2-Squad11 pull request #48
Opened 2023-10-14 20:08 UTC by henriquecq

Issue : 
#40 

O que foi feito:
- Foram definidas as principais rotas da API, incluindo as URLs base para diferentes partes do aplicativo.
- Especificados os métodos HTTP suportados para cada rota (por exemplo, GET, POST, PUT, DELETE).

2023-10-14 20:39 UTC, caio-felipee requested changes
Boa tarde. Eu tenho algumas preocupações em relação à definição de rotas da API:

1. O primeiro problema é em relação ao erro que aparece ao definir o `body` e `header` no Markdown, mas julgo como "ok" para ser aceito.
2. O segundo é a [Consulta da Grade de Matérias](https://github.com/unb-mds/2023-2-Squad11/blob/c5827420ef7a8bebd18ea31ad615e4d502641aa5/docs/api.md#consulta-da-grade-de-mat%C3%A9rias). Na minha visão, a resposta devia ser adequada para enviar mais de uma grade. Adicionalmente, sinto falta de algumas informações como "nome do professor", "sala" e "turma". 

O protótipo do **web-scraping** já foi realizado e temos algumas informações coletadas importantes, que podem ser encontradas nos comentários do [código](https://github.com/unb-mds/2023-2-Squad11/blob/main/api/api/utils/web_scraping.py). 

3. O terceiro é em relação a mistura do português com o inglês na definição das chaves da [visualização de perfil](https://github.com/unb-mds/2023-2-Squad11/blob/c5827420ef7a8bebd18ea31ad615e4d502641aa5/docs/api.md#visualiza%C3%A7%C3%A3o-de-perfil). 

4. É interessante receber o código das matérias que estão sendo lidadas na [montagem de grade](https://github.com/unb-mds/2023-2-Squad11/blob/c5827420ef7a8bebd18ea31ad615e4d502641aa5/docs/api.md#montagem-de-grade), uma vez que a chave atual do nosso *web-scraping* recebe o código da matéria como parâmetro. Isto vale também para o [update de grade](https://github.com/unb-mds/2023-2-Squad11/blob/c5827420ef7a8bebd18ea31ad615e4d502641aa5/docs/api.md#update-de-grade).

2023-10-15 13:06 UTC, mateusvrs requested changes
Bom dia, algumas coisas que devem ser corrigidas:

- A parte de autênticação do projeto já está implementada com as respectivas rotas, portanto, é necessária a atualização de acordo com o código produzido na issue #47.
- O `body` e `headers` estão fora do padrão `json` como o @caio-felipee mencionou, para corrigir esse problema recomendo utilizar `js` como linguagem dos blocos de código.

Segue exemplo:

---

### Nome do App Django

Método HTTP `/path/to/http/request`: Descrição da função

- Request:

    ```js
    Authorization: Bearer <access-token>
    Cookie: refresh=<refresh-token>
    body: {
        
    }
    ```

- Response:

    ```js
    HTTP/1.1 200 OK
    Content-Type: application/json
    Set-Cookie: refresh=<refresh-token>; Secure; HttpOnly; SameSite=Lax; Expires=<expires-date>
    body: {

    }
    ```

---

Para mais informações sobre os códigos de status HTTP, recomendo a leitura do site [MDN HTTP Status](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status). Além disso, é importante entender sobre os métodos HTTP e quando utilizá-los, para isso, deve-se [MDN HTTP Methods](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods). Por fim, é importante entender sobre os cabeçalhos HTTP que estão descritos em [MDN HTTP Headers](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers).

2023-10-18 17:25 UTC, henriquecq commented
Alterei o arquivo conforme indicado, agradeço as colocações.

2023-10-19 01:43 UTC, caio-felipee approved these changes

2023-10-19 01:43 UTC, mateusvrs approved these changes

2023-10-19 01:43 UTC, GabrielCastelo-31 approved these changes
### LGTM

2023-10-19 01:44 UTC, merged