api(search):
unb-mds/2023-2-Squad11 pull request #82
Opened 2023-11-14 02:01 UTC by caio-felipee

**Issue:**
close #62 

**O que foi feito?**
- Adicionado o plugin `unaccent` no PostgreSQL para facilitar na pesquisa com irrelevância na acentuação
- Criado o arquivo `serializers.py` para adicionar os serializers necessários para a Response da API
- Alterado o arquivo `urls.py` para adição da nova rota da api `/courses`
- Criada a API que utiliza os parâmetros `search`, `year` e `period`
- Criada funções de filtragem no banco de dados

2023-11-16 02:47 UTC, henriquecq approved these changes

2023-11-17 04:28 UTC, mateusvrs requested changes

2023-11-17 04:28 UTC, mateusvrs commented on api/api/views.py
> +        disciplines = filter_disciplines_by_name(name=name[0])
Boa noite, observei que nesse trecho de código da linha 25 há um caso em que o servidor dá um erro indevido (500 Interval Server Error). Isso visto que há um acesso direto ao primeiro elemento da lista gerada por `name.split()`, mas caso o request do usuário seja: `/courses/?search=%20&year=2023&period=2`, em que `%20` representa um espaço em branco ` `, a lista gerada por `name.split()` será vazia e o Python não poderá acessar a posição inicial mostrando um `IndexError`.

Dessa forma, recomendo adicionar uma função que trata as strings `name`, `year` e `period` recebidas do usuário de forma que sejam retirados os espaços desnecessários antes da utilização dessas variáveis, recomendo a inserção do seguinte código, entre as linhas 13 e 23:

```py
class Search(APIView):
    def treatsString(self, string: str | None) -> str:
        if string is not None:
            string = string.strip()

        return string

    def get(self, request: Request, *args, **kwargs) -> Response:
        name = self.treatsString(request.GET.get('search', None))
        year = self.treatsString(request.GET.get('year', None))
        period = self.treatsString(request.GET.get('period', None))
```

Não é necessário a adição desse código puramente como está, recomendo obserção e avaliação.

Por fim, recomendo que esse caso de teste seja adicionado nos testes no arquivo `api/api/tests.py`. :purple_heart:

2023-11-17 04:28 UTC, mateusvrs commented on api/api/views.py
> +from django.db.models import QuerySet
Aqui a classe `QuerySet` não está sendo utilizada durante o código, acredito que a linhas possa ser removida.

2023-11-17 04:28 UTC, mateusvrs commented on api/api/serializers.py
> +        fields = ('code', 'year', 'period')
Observa-se na [documentação](https://www.django-rest-framework.org/api-guide/serializers/#specifying-which-fields-to-include) do Django Rest Framework que caso você queira que o `ModelSerializer` realize as operações com _todos_ os campos da minha `model` que foi passada não é necessário lista-los, apenas colocar `'__all__'`. O mesmo segue para as linhas 12 e 20. Recomendo rodar os testes novamente após a alteração par ter certeza da troca.

2023-11-17 04:28 UTC, mateusvrs commented on api/api/tests.py
> +from .views import Search, ERROR_MESSAGE
A classe `Search` não está sendo utilizado durante os testes acredito que pode ser retirada das importações.

2023-11-17 20:19 UTC, caio-felipee commented on api/api/views.py
> +        disciplines = filter_disciplines_by_name(name=name[0])
Resolvido! Agradeço pela observação minunciosa do código no qual não deixou escapar este erro. :partying_face:

2023-11-17 22:27 UTC, mateusvrs approved these changes

2023-11-17 22:41 UTC, merged